apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery
spec:
  selector:
    matchLabels:
      app: gallery
  template:
    metadata:
      labels:
        app: gallery
    spec:
      containers:
      - name: gallery
        image: samuelroweuk/gallery:latest 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gallery
  name: gallery
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gallery
  type: LoadBalancer