apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gallery
  name: gallery
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: gallery
  type: LoadBalancer