## Azure DevOps pipeline to build and push docker image to DockerHub. 
## I usually push to Azure Container Registry but this is open source project so might as well
## make the container image public as well as source.
pool:
  vmImage: 'ubuntu-18.04'

resources:
  repositories:
    - repository: dockerfgallery 
      type: github
      name: Sam-Rowe/docker-fgallery
      endpoint: GitHub-Demo-Connection

jobs:
  - job: build
    steps:
    - checkout: dockerfgallery
    - task: Docker@2
      inputs:
        containerRegistry: 'Demos-samuelrowe-ms'
        repository: 'samuelroweuk/gallery'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: sed -i -E 's/:latest\s/:$(Build.BuildId)/g' k8s/gallery-deployment.yml
    - task: CopyFiles@2
      inputs:
        contents: 'k8s/**'
        targetFolder: $(Build.ArtifactStagingDirectory)
        condition: always()
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: gallery-k8s
        condition: always()